[package]
name = "phrase-set-variations"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-bert = "0.7.2"
rand = "0.7.3"
tch = "0.1.7"